version: "3.9"
services:
  db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: desafio_development
      POSTGRES_PASSWORD: desafiopass
    volumes:
      - ./.data:/var/lib/postgresql/data
