default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV['RAILS_MAX_THREADS'] || 5 %>
  url: <%= ENV['DATABASE_URL'] %>

development: &development
  <<: *default
  database: desafio_development
  username: postgres
  password: desafiopass
  host: 127.0.0.1

test:
  <<: *default
  database: account_test<%= ENV['TEST_ENV_NUMBER'] %>
  username: postgres
  password: desafiopass
  host: 127.0.0.1

  profile:
    <<: *development

sandbox:
  <<: *default

production:
  <<: *default
